

jobs:
- job: infrastructure
  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    AZURE: 'MSDN_950_kr'

  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      projects: 'src'
      zipAfterPublish: false
      modifyOutputPath: false
    displayName: 'Build and publish ASP.NET Core app'
  - task: Npm@1
    inputs:
      command: 'install'
      workingDir: 'infra'  
    displayName: 'NPM install packages'
  
  - task: Pulumi@0
    inputs:
      azureSubscription: $(AZURE)
      command: 'up'
      args: '--yes'
      cwd: 'infra'
      stack: 'dev'
    displayName: 'Install pulumi and run infra code'
    name: pulumi
